#!/usr/bin/env bash
set -euo pipefail
repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
media="$repo_dir/media"; output="$media/DAGstronaut-demo-v2.mp4"
font="/System/Library/Fonts/Supplemental/Arial Bold.ttf"
work="$(mktemp -d /tmp/dagstronaut-v2.XXXXXX)"; trap 'rm -rf "$work"' EXIT
encode=(-an -r 30 -c:v libx264 -preset medium -crf 18 -pix_fmt yuv420p -color_primaries bt709 -color_trc bt709 -colorspace bt709 -f mpegts)
fit="scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:0x07111f"

ffmpeg -v warning -y -f lavfi -i color=0x07111f:s=1920x1080:r=30:d=3 -vf "drawtext=fontfile='$font':text='THIS DAG DOES NOT MOVE DATA.':fontcolor=white:fontsize=64:x=(w-text_w)/2:y=400,drawtext=fontfile='$font':text='IT MOVES A ROVER.':fontcolor=0xffc857:fontsize=78:x=(w-text_w)/2:y=500,drawtext=fontfile='$font':text='DAGSTRONAUT':fontcolor=0x55d9ff:fontsize=28:x=(w-text_w)/2:y=650" -t 3 "${encode[@]}" "$work/00.ts"
ffmpeg -v warning -y -i "$media/DAGstronaut-intro.mp4" -vf "$fit,drawtext=fontfile='$font':text='MEET DAGSTRONAUT':fontcolor=0x55d9ff:fontsize=52:x=70:y=55,drawtext=fontfile='$font':text='AN AIRFLOW-ORCHESTRATED ROVER':fontcolor=white:fontsize=28:x=73:y=120" -t 5 "${encode[@]}" "$work/01.ts"
ffmpeg -v warning -y -ss 2 -i "$media/DAGstronaut-section2-rover-run.mp4" -vf "$fit,drawbox=x=36:y=35:w=720:h=58:color=0x07111f@0.82:t=fill,drawtext=fontfile='$font':text='SYSTEMS CHECK  >  EXPLORATION  >  OBSTACLE DETECTION':fontcolor=0xffc857:fontsize=25:x=58:y=51" -t 10 "${encode[@]}" "$work/02.ts"
ffmpeg -v warning -y -ss 13 -i "$media/DAGstronaut-section2-rover-run.mp4" -vf "$fit,drawbox=x=36:y=35:w=730:h=96:color=0x07111f@0.84:t=fill,drawtext=fontfile='$font':text='CAMERA EVIDENCE + LOCAL VISION AI':fontcolor=0x55d9ff:fontsize=28:x=58:y=50,drawtext=fontfile='$font':text='Common AI @task.llm  |  Gemma 3 Vision':fontcolor=white:fontsize=23:x=58:y=91" -t 7 "${encode[@]}" "$work/03.ts"
ffmpeg -v warning -y -stream_loop -1 -ss 22.5 -i "$media/DAGstronaut-section2-rover-run.mp4" -vf "$fit,drawbox=x=36:y=35:w=565:h=96:color=0x07111f@0.84:t=fill,drawtext=fontfile='$font':text='HUMAN-IN-THE-LOOP':fontcolor=0xffc857:fontsize=30:x=58:y=50,drawtext=fontfile='$font':text='AI advises. A human authorizes.':fontcolor=white:fontsize=23:x=58:y=92" -t 9 "${encode[@]}" "$work/04.ts"
ffmpeg -v warning -y -i "$media/DAGstronaut-section3-flight-director-console.mp4" -vf "$fit,drawbox=x=36:y=35:w=680:h=96:color=0x07111f@0.84:t=fill,drawtext=fontfile='$font':text='FLIGHT DIRECTOR CONSOLE':fontcolor=0x55d9ff:fontsize=30:x=58:y=50,drawtext=fontfile='$font':text='Airflow HITL on a physical five-inch display':fontcolor=white:fontsize=22:x=58:y=92" -t 7 "${encode[@]}" "$work/05.ts"
ffmpeg -v warning -y -stream_loop -1 -i "$media/dagstronaut-mission-loop-v3.gif" -vf "$fit,drawtext=fontfile='$font':text='AUTHORIZED BRANCH':fontcolor=0xffc857:fontsize=42:x=(w-text_w)/2:y=42,drawtext=fontfile='$font':text='Airflow orchestrates the return path':fontcolor=white:fontsize=27:x=(w-text_w)/2:y=95" -t 8 "${encode[@]}" "$work/06.ts"
ffmpeg -v warning -y -stream_loop -1 -ss 4.2 -i "$media/planet-exploration-rover.gif" -vf "$fit,drawbox=x=0:y=0:w=1920:h=112:color=0x07111f@0.88:t=fill,drawtext=fontfile='$font':text='MISSION COMPLETE':fontcolor=0x70dfa0:fontsize=44:x=(w-text_w)/2:y=24,drawtext=fontfile='$font':text='Return path and mission report complete':fontcolor=white:fontsize=23:x=(w-text_w)/2:y=76" -t 5 "${encode[@]}" "$work/07.ts"
ffmpeg -v warning -y -f lavfi -i color=0x07111f:s=1920x1080:r=30:d=6 -vf "drawtext=fontfile='$font':text='DAGSTRONAUT':fontcolor=0x55d9ff:fontsize=66:x=(w-text_w)/2:y=245,drawtext=fontfile='$font':text='AIRFLOW 3.3  |  COMMON AI  |  HITL  |  REACT PLUGIN':fontcolor=white:fontsize=31:x=(w-text_w)/2:y=395,drawtext=fontfile='$font':text='AIRFLOW CAN DO THAT?!':fontcolor=0xffc857:fontsize=52:x=(w-text_w)/2:y=515,drawtext=fontfile='$font':text='The rover explores. AI advises. A human commands. Airflow brings it home.':fontcolor=0xb8c2d1:fontsize=24:x=(w-text_w)/2:y=630" -t 6 "${encode[@]}" "$work/08.ts"

ffmpeg -v warning -y -i "concat:$work/00.ts|$work/01.ts|$work/02.ts|$work/03.ts|$work/04.ts|$work/05.ts|$work/06.ts|$work/07.ts|$work/08.ts" -i "$media/DAGstronaut-demo.mp4" -map 0:v -map 1:a -c:v copy -af "volume=8dB,alimiter=limit=0.89,apad=pad_dur=9,atrim=duration=60,afade=t=in:st=0:d=0.5,afade=t=out:st=58.5:d=1.5" -c:a aac -b:a 192k -ar 48000 -movflags +faststart -t 60 "$output"
printf 'Created %s\n' "$output"
